name: Deploy to WordPress.org

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build ZIP
        run: bash ./build/build-zip.sh

      - name: Deploy via 10up action
        uses: 10up/action-wordpress-plugin-deploy@v2
        with:
          generate-zip: false
          # Your plugin "slug" directory name in the wp.org SVN
          slug: ac-advanced-flamingo-settings
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

